### ISSUE TITLE
[Bug] Debugger is not appearing.

### ISSUE THREAD

**Issue by Zensonaton** [murugaratham/vscode-dotnet-watch#10]
Hello. For some reason, after running debug configuration:
```json
{
	"type": "DotNetWatch",
	"request": "launch",
	"name": ".NET Core Watch",
	"args": [],
	"project": "Project.csproj",
	"env": {
		"ASPNETCORE_ENVIRONMENT": "Development"
	}
}
```
Debugger is not appearing; breakpoints are completely ignored, I can't control debugging session because "debugging menu" is not appearing on top, etc.

In the "Output" tab there is next line appearing after attempting to start debugging session: `Problem matcher {0} can't be resolved. The matcher will be ignored`.
Task called "Watch" exists in "Terminals" tab.

System: `Manjaro (Arch) Linux`, Extension version `v1.1.1`, .NET version `6.0.102`.

**Comment by murugaratham** [comment]
I don’t have an arch Linux environment to try out, but can you try running dotnet watch via cli and see if debugger attaches?

**Comment by Zensonaton** [comment]
Tried both `dotnet run` and `dotnet watch`, and no, debugger does not attaches automatically.
Created `.NET Core Attach` task, and it works properly.

Still, there is a `Problem matcher {0} can't be resolved. The matcher will be ignored` error when trying to run debug configuration from extension.

**Comment by murugaratham** [comment]
I doubt problemMatcher is causing issue, can I trouble you to clone this repo and launch a debug instance of vscode extension host and set breakpoint on exceptions? 

Unless I can find time to get my hands on recreating an environment

**Comment by Zensonaton** [comment]
Okay then, I'll clone the repo and try to debug it.

**Comment by Zensonaton** [comment]
Tried to debug, and there is a problem that I noticed:

https://github.com/murugaratham/vscode-dotnet-watch/blob/4d2c19e56fc83edacd1dc1493d7ab5b09a5010f0/src/services/task-service.ts#L128
it should be `$msCompile`, not `$mscompile` :D
However, this change only removes the "problem matcher can't be resolved", extension still does not start the debugging session.

**Comment by Zensonaton** [comment]
Right after sending previous comment, I alt+tabbed to VSCode, and noticed next error in "Debug Console":
```
error: improper format list

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```
:eyes:

**Comment by murugaratham** [comment]
Oh, what’s the command for listing process on arch? It’s trying to list running debugging processes (tasks) spawned by the extensions, we are getting somewhere

**Comment by murugaratham** [comment]
See https://github.com/murugaratham/vscode-dotnet-watch/blob/4d2c19e56fc83edacd1dc1493d7ab5b09a5010f0/src/services/process-service.ts#L55

**Comment by Zensonaton** [comment]
Tested it, and `ps -o pid,ppid,command` works properly.
"improper format list" error can be fixed by changing
https://github.com/murugaratham/vscode-dotnet-watch/blob/4d2c19e56fc83edacd1dc1493d7ab5b09a5010f0/src/services/process-service.ts#L56-L58
to
```ts
const tmp = child_process.execSync("ps -o pid,ppid,command").toString();
```

**Comment by murugaratham** [comment]
Interesting, I’ll test on mac and would need to get my hands on windows before releasing it

**Comment by murugaratham** [comment]
thanks @Zensonaton for reporting this and helping in troubleshooting, i've released v1.1.3, you should be able to see it once marketplace decides to propagate

**Comment by Zensonaton** [comment]
Great! I'll wait for the update to arrive, and I'll answer in this thread if something goes wrong :upside_down_face:

**Comment by Zensonaton** [comment]
So, after checking updated extension, I found out that it is not working :disappointed: 
I debugged it by myself, and found out that `getProcessDetailsFromUnix` function is a culprit in this problem: `child_process.execSync(...)` was executed, but only few processes got listed because of how Linux's `ps` works :D
After my fix, extension worked, but I found out that for some reason debugger got attached and disconnected at the same moment; I was able to 'pause' the execution of dotnet code, but my breakpoints were ignored.

I've made [a PR](https://github.com/murugaratham/vscode-dotnet-watch/pull/11) with `ps` fix and a "fix" to a debugger that was connecting disconnecting at the same time. Please look into the second commit, because fix I made is actually bad and it will break some things :D
