### ISSUE TITLE
No Instance(s) Available.

### ISSUE THREAD

**Issue by moalamri** [murugaratham/vscode-dotnet-watch#13]
Hi,
Thanks a lot for saving time to manually attach every time (That used to bother me a lot haha)
Anyways, I notice that the editor gets bit heavy when using the auto attach. 
I Couldn't figure why but looking at the editor console `CTRL + SHIFT + i` it gets flooded by `No Instance(s) Available.` error from VS Code's Extension Host.

It stops once I stop the debug session. And never shows when I manually attach to the dotnet host.
It also shows the same when I use the original repo.

I use Windows 11 x64. Let me know if I can help to debug this further.
Thank you.

**Comment by murugaratham** [comment]
Hi @moalamri,

The extensions attempts to attach a debugger process every 1000ms, afterwhich, it detects the platform, in your case `win32`, after which, it will run `wmic process get ProcessId,ParentProcessId,CommandLine` if there's not parentId (debugger process). 

If there is, it will execute a "filtered" like by running `wmic process where parentProcessId={ppid} get ProcessId,ParentProcessId,CommandLine` 

Need to understand more regarding the "heaviness", can you show [process explorer](https://www.infoworld.com/article/3602661/6-neat-tricks-for-visual-studio-code.html) and see how much CPU it's consuming, (sorry i dont have a windows machine to test).

A possible "solution" would be to adopt what is suggested (here)[https://superuser.com/questions/1082685/how-to-treat-the-no-instance-found-of-wmic-command-in-batch], essentially, it's redirecting the errors to nul.

Let me know and i can see if we should add it to the extensions, although it's more or a hinderance rather than a real hog

**Comment by moalamri** [comment]
Hi @murugaratham 

I have looked into the code in an attempt to spot the "reason" where I saw some of the steps you mentioned.
The heaviness is not in the editor itself, but it's something of how VS Code works by suppressing other processes in an attempt to make the unresponsive extension to finish (Starting a CPU Profiler at the same time), so it's not high CPU usage or laggy UI, but more of "hold it there other extensions, it's my turn" 😄 
Here's the profiler message generated by the extension host 
```log
WARN UNRESPONSIVE extension host: 'Murugaratham.vscode-dotnet-watch' took 100% of 792.294ms, saved PROFILE here: 'file:///c%3A/Users/mohammed/AppData/Local/Temp/exthost-280667.cpuprofile
```
Here's the CPU Profile, it's not huge, but zipped so I can upload it here:
[exthost-280667.zip](https://github.com/murugaratham/vscode-dotnet-watch/files/9347829/exthost-280667.zip)

Use VS Code itself to view the profile, I didn't know it has a built-in cpuprofile visualizer (Thank you for that as well 👍🏻) it can give you a cleaner sight of the above warn message.

I will read the article you mentioned and also look closely at the profile tomorrow.
Thank you so much 👍🏻

**Comment by murugaratham** [comment]
I’m pretty occupied at work, will have a look when I can get time. But we don’t get this unresponsive extension host warning over at other OS, I’m on intel & arm macs, I’ve seen someone on Arch Linux too. 

I’ll try to see what’s going on, but might need your help to see what’s churning the cpu. 

If you have time, can u clone this project and run it as extension host and reproduce?

**Comment by moalamri** [comment]
> I'm pretty occupied at work 
Why does that sound very familiar?  😂
It's totally ok, take your time. it's not a big deal.
I will have a look today and see what I could come up with. 

Just a quick question, I have an AMD. If that's the reason then it could be a user side issue and nothing related to the extension it self? If no then that will make it easier for me to debug (because I don't know much about CPU architecture and if they impact a role in there)

**Comment by moalamri** [comment]
Unfortunately debugging the source code didn't give a much of context, the same error but in debug console this time. I tried to change the cmd of windows to use pwsh (Which supports `ps`) , but got even more complicated error, as I need to re-adjust the parsing regex. Anyways I saw something, It fixed the issue when I changed it, but the extension wasn't able to auto-attach to the .NET Host anymore, shouldn't we [use the ParentProcessId (ppid) here](https://github.com/murugaratham/vscode-dotnet-watch/blob/b49086e370e11df88807768811ac9224a2e43dd0/src/services/process-service.ts#L128)?

**Comment by murugaratham** [comment]
not really, we are looking for child processes, is there any stuff that's churning during ur debug run?

**Comment by moalamri** [comment]
Nothing at all. Except that VS Code is able to find all children by only attaching to the parent. The extension caches 3-4 children before throwing the `No Instance(s)` error. 
While at the debug panel of VS Code I can see all the children which they were 9 🤯

I will close this issue until later when we both could find a better time to invest into this issue. It is not that big of a problem, perhaps when I find time I'll see if VS Code would auto-attach to the dotnet host and monitor its children by only passing the process id in your extension.

**Comment by moalamri** [comment]
Hi,
I was able to use VS Code's launch & tasks to run and auto-attach

`launch.json`
```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "dotnet watch",
      "request": "launch",
      "type": "coreclr",
      "cwd": "${workspaceFolder}/BackEnd/WebApi",
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
      },
      "console": "integratedTerminal",
      "program": "dotnet",
      "suppressJITOptimizations": true,
      "args": [
        "watch",
        "--project",
        "./"
      ],
      "presentation": {
        "hidden": true,
      }
    },
    {
      "name": "attach to dotnet",
      "type": "coreclr",
      "request": "attach",
      "processName": "WebApi",
      "presentation": {
        "hidden": true
      },
      "preLaunchTask": "timeout-3"
    },
  ],
  "compounds": [
    {
      "name": "Run Dev",
      "configurations": ["dotnet watch", "attach to dotnet"]
    }
  ]
}
```

`tasks.json`
```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "timeout-3",
      "type": "shell",
      "command": "timeout 3",
      "hide": true,
      "presentation": {
        "echo": false,
        "reveal": "never",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": false,
        "clear": false,
        "close": true
      }
    }
  ]
}
```

The `"preLaunchTask"` is basically to give some fake task for few seconds so the project process will be already running and available in the process list. then VS Code will auto attach to the selected `"processName"`

If someone facing the same issue with Windows you can suggest this solution without using any extension so you can get rid of the overhead problem :0

Thank you again 👍🏻
