### ISSUE TITLE
Support ${workspaceFolder} in the "project" configuration

### ISSUE THREAD

**Issue by devantler** [murugaratham/vscode-dotnet-watch#14]
Right now, a full path to a .csproj file is needed when setting a default project path to watch.

```json
{
    "type": "DotNetWatch",
    "request": "launch",
    "name": ".NET Core Watch (web)",
    "project": "/Users/username/project-folder/ProjectName/ProjectName.csproj",
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
},
```

It would be nice if we could use the ${workspaceFolder} variable as with normal launch configs:

```json
{
    "type": "DotNetWatch",
    "request": "launch",
    "name": ".NET Core Watch (web)",
    "project": "${workspaceFolder}/ProjectName/ProjectName.csproj",
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
},
```

Currently, this does not seem to work, and I have not been able to find a way around this other than giving the full path, which I would rather avoid, as it makes the launch configuration rely on the project's path.

**Comment by murugaratham** [comment]
Sounds like a good idea, I’ll take a look

**Comment by murugaratham** [comment]
@devantler, i've tested with a minimal `dotnet new console` it works when i have multiple project folder and `.csproj`, feel free to reopen if it's not working for you.

**Comment by murugaratham** [comment]
Though I fixed this edge case, I wasn’t really happy with the way I fixed it lol, documentation is quite sparse on how to handle vscode variables, but glad that it worked for you.
