### ISSUE TITLE
launchBrowser not working due to double quotes

### ISSUE THREAD

**Issue by nelisbijl** [murugaratham/vscode-dotnet-watch#16]
I am using .Net 7 on macOS
Observations:
- The intellisense in launchSettings.json indicate that launchBrowser can only be a boolean. This contradicts the suggestions in the documentation and other issues
- Starting a browser depends on the 'Now listening on' log message from Microsoft.Hosting.Lifetime. When suppressed, nothing happens

The 'Now listening on' message has been changed somewhere in .Net. It now includes double quotes around the url. When trying to open "http://localhost:5000"/api-docs, the 'url' is not seen as such, but as a subfolder of the {workspaceFolder}. Thus opening fails with 'The file ... does not exist.'

**Comment by murugaratham** [comment]
I’m on reservist and will only have time in a couple of weeks, will take a look, prs are welcomed too

**Comment by nelisbijl** [comment]
Seems an issue in .NET itself. Other dotnet watch plugins suffer the same issue. However I found one that allows a serverReadyAction in the launch config (yours does not). You can either set launchBrowser to false or simply ignore the warning in the logs. The launch is then performed by serverReadyAction.

**Comment by murugaratham** [comment]
Thanks for updating, to make it easier, will you be able to create a minimal repro? I’m getting some time soon, will try to see

**Comment by murugaratham** [comment]
@nelisbijl i do not understand your problem, i've just tried on dotnet 8 webapi, doesn't seem to have any problem

![image](https://github.com/murugaratham/vscode-dotnet-watch/assets/653805/fe0e5dda-8ff2-486d-b44e-b521a52fdf0e)

**Comment by nelisbijl** [comment]
In your case the url after 'Now listening on:' has no double quotes around it. In my case it has. 
Further investigation shows that those quotes are added by Serilog.
Sorry for the inconvenience, this issue can be closed

**Comment by murugaratham** [comment]
Alright, thanks for getting back
