### ISSUE TITLE
How to support opening a browser when starting?

### ISSUE THREAD

**Issue by winzig** [murugaratham/vscode-dotnet-watch#3]
Migrating from the normal "coreclr" configuration to this to take advantage of "hot reload," but not able to figure out how to get the browser launching like I could do previously with coreclr debugging. Any ideas?

Previously I could use:

```
"launchBrowser": {
    "enabled": true,
    "args": "http://localhost:5000/",
    "windows": {
        "command": "cmd.exe",
        "args": "/C start http://localhost:5000/"
    },
    "osx": {
        "command": "open"
    },
    "linux": {
        "command": "xdg-open"
    }
}
```

**Comment by murugaratham** [comment]
You can do this in launch.json

```
{
	"type": "DotNetWatch",
	"request": "launch",
	"name": ".NET Core Watch: yourproject.Api",
	"env": {
		"ASPNETCORE_ENVIRONMENT": "Development",
		"DOTNET_WATCH_RESTART_ON_RUDE_EDIT": "true"
	},
	"launchBrowser": {
		"enabled": true,
		"args": "${auto-detect-url}",
		"windows": {
			"command": "cmd.exe",
			"args": "/C start ${auto-detect-url}"
		},
		"osx": {
			"command": "open"
		},
		"linux": {
			"command": "xdg-open"
		}
	}
}
```

**Comment by winzig** [comment]
I've got nearly that identical `launchBrowser` in my launch.json, and it never launches the browser. I'm on macOS 12.x. It works fine when I use the original coreclr debug method.

**Comment by winzig** [comment]
I just noticed I'm seeing this error appear when I choose "Start Debugging":

> Error opening launch profile [/Users/.../Properties/launchSettings.json]: Error: cannot open file:///Users/.../Properties/launchSettings.json. Detail: Unable to read file '/Users/.../Properties/launchSettings.json' (Error: Unable to resolve nonexistent file '/Users/.../Properties/launchSettings.json')

(The `...` in the error is just for privacy, the path is otherwise correct in the error.) I don't normally experience this error.

**Comment by murugaratham** [comment]
The default .net template generates launchSettings.json

![image](https://user-images.githubusercontent.com/653805/155642718-d16496a2-7f50-41a2-8643-e17a31816ff0.png)

I was deliberating whether or not to try load launchProfiles, but when i noticed all default templates seems to provide `launchSettings.json` i went ahead to hardcode this, can you share how you create your project?

**Comment by murugaratham** [comment]
Published new release to not prompt error message if can't find launchSettings.json

https://github.com/murugaratham/vscode-dotnet-watch/blob/c504c1dee0b975d485e8b99f5a961bfb06578c14/src/services/task-service.ts#L137

You can try scaffold a default launchSettings & control the `launchBrowser` behavior there instead

**Comment by winzig** [comment]
I created this project in 2018 and at the time, it did come with launchSettings.json, but over time we realized we were not using any features of launchSettings.json. (It's been so long now that I can't even remember what the point of launchSettings.json was.) 

I see the 1.1.0 release on the releases page, but not yet showing up within vscode extensions area. The latest asset on the releases page is for the 1.0.4 vsix file. How does one build this project? Thanks!

**Comment by winzig** [comment]
OK I see now that 1.0.4 is the newest version that fixes launchSettings error, however, launchBrowser still does not seem to be working for me. When I "Start Debugging," no more errors, but still no browser launch as it does when I use the traditional `coreclr` debug task.

My task definition currently looks like this (some of these things are copied from `coreclr` and may not apply to your debugger):

```
{
    "type": "DotNetWatch",
    "request": "launch",
    "name": ".NET Core Watch: Web",
    "project": "/Users/tom/path-to-my-project/Web.csproj",
    "args": ["/property:GenerateFullPaths=true"],
    "launchBrowser": {
        "enabled": true,
        "args": "http://localhost:5000/",
        "windows": {
            "command": "cmd.exe",
            "args": "/C start http://localhost:5000/"
        },
        "osx": {
            "command": "open"
        },
        "linux": {
            "command": "xdg-open"
        }
    },
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    },
    "sourceFileMap": {
        "/Views": "${workspaceRoot}/Views"
    }
}
```

**Comment by murugaratham** [comment]
You don’t have to configure these in task definition, just create a folder “Properties”, then a file “launchSettings.json”. 

Or just run dotnet new console and copy the launch settings into your project

**Comment by winzig** [comment]
Are you saying launchBrowser will only work if I have a launchSettings.json file? Even though in my tasks.json, the launchBrowser object is as shown above?

**Comment by murugaratham** [comment]
I've tested a few combinations on `launchBrowser` configuration, it seems like i'm only able to launch by setting it in launchSettings.json

```
"test": {
      "commandName": "Project",
      "nativeDebugging": false,
      "launchBrowser": true,
      "dotnetRunMessages": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7126;http://localhost:5069",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
```
`serverReadyAction` is not supported on debug console while using dotnet watch, see https://github.com/microsoft/vscode/issues/96294
