### ISSUE TITLE
The debugger and the `dotnet watch run` process dies whenever I save a file.

### ISSUE THREAD

**Issue by devantler** [murugaratham/vscode-dotnet-watch#9]
The extension is not working well for me. Whenever I save a file the debugger and the `dotnet watch run` process dies.

My launch.json files looks like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "DotNetWatch",
            "request": "launch",
            "name": ".NET Core Watch",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "DOTNET_WATCH_RESTART_ON_RUDE_EDIT": "true"
            }
        }
    ]
}
```

And I am building a Blazor Server App on MacOS with .NET 6.

Does the extension throw logs somewhere so I can share them here, in case they point to the problem? :-)

**Comment by murugaratham** [comment]
Do you see it in extension host?

**Comment by devantler** [comment]
No, there is nothing there when it dies. It does give me a `ProblemMatcher{0} ignored` (in the Tasks log) when I start the debugging session with the extensions launch config. Maybe that is related.

**Comment by murugaratham** [comment]
Will you be able to give a minimal repro? Haven’t done blazor

**Comment by murugaratham** [comment]
I am able to repro by ``

but even during debugging of the extesion, the debugger process just crashes.

What the extension does, is quality of life improvements, where it generates a task and attach via vs code debugger service.

![image](https://user-images.githubusercontent.com/653805/168941218-c94efca6-fd23-43fd-80d7-0c087952d357.png)

Strange part is that, when i run the similar dotnet watch command on a seperate terminal, it works fine

It seems like blazor debugging on vscode is still quirky, there's several issues pointing to it 

https://github.com/OmniSharp/omnisharp-vscode/issues/5128
https://github.com/OmniSharp/omnisharp-vscode/issues/5183

I'll keep the issue open and see if omnisharp has any update

**Comment by devantler** [comment]
Thanks! I will keep an eye for any updates as well. Hopefully it gets fixed soon, as I envy the productivity I am missing! 😉

**Comment by IntoLighter** [comment]
I encountered the same for Razor Pages app.

**Comment by murugaratham** [comment]
@IntoLighter are you able to give a minimal repro?

**Comment by IntoLighter** [comment]
@murugaratham https://github.com/IntoLighter/Marketplace

**Comment by murugaratham** [comment]
I've published a new release, take a look when you updated the extension, I'll keep the issue open for awhile

**Comment by murugaratham** [comment]
fixed with latest release, feel free to reopen if debugger is still detaching
